### ISSUE TITLE
A beginner guide/prerequisites for setting up your system to Airplonk

### ISSUE THREAD

**Issue by patrickm663** [daaanstraight/AirPlonk#5]
Hi @gomesdigital

Thanks for putting this together.

On the installation side, the guide is quite clear (using Ubuntu and Termux), however some dependency issues (my side at least) meant I had to swap commands.

My main issue is picking up available ports. For someone starting from scratch, would you be able to provide pointers on how to get that set up? I can offer to create a basic Ubuntu userguide for getting that set up once I've figured it out?

Additionally, do you have experience using this to plonk to a virtual machine?

Cheers,
Patrick Moehrke

**Comment by gomesdigital** [comment]
Hey @patrickm663 !

Thanks for reaching out. 

Did your installation go smoothly? I just tested the .deb on Ubuntu 20.10 and didn't face any dependency issues...

I'd be happy for you to contribute!

First, could you mention which commands you ended up using for a fix? Then I can have a bit more context of what the troubles might be here.

**Comment by patrickm663** [comment]
Hey @gomesdigital 

Sorry I'm only getting back to this now but happy to report it is now working on my system :)

Here is what I found worked on my side and some other things I have tested if they're maybe useful:

1. The issue I had faced on my Ubuntu install was caused by it throwing an error after running the `dpkg` command. I think I had interpreted the missing dependencies as it throwing an error. I did a fresh install using v1.0.2 and everything worked as expected.
2. Next up (on my PC at least) was setting up an SSH server. The link provided in the help file (https://opensource.com/article/20/9/ssh) was useful for setting up OpenSSH and it boiled down to the following commands:
`$ sudo apt update`
`$ sudo apt install openssh-server openssh-client # adding --reinstall may help fix "unit file sshd.service not found" errors`
`$ sudo systemctl start sshd`
Then, running `airplonk` lists at least my local machine as an available node.
3. On Termux for Android, the following worked to install and set up OpenSSH:
`pkg install openssh`
`sshd # Activate it`
`pkill sshd # End it`
(This however runs on port 8022 on non-root devices (instead of port 22) which is why I suspect it does not come up under available ports even though I am able to SSH to and from it?).
4. I also wanted to try AirPlonk between a VM and my host machine. I set up Fedora 35 and wrote a short modified installation script to install missing dependencies (based off the Termux installation script). The dependencies needed were `expect hostname nmap rsync`.
![Screenshot of AirPlonk working on Fedora 35](https://user-images.githubusercontent.com/77886027/146682651-0cc65dac-979e-4e49-99a8-fe223c610574.png)
5. On a VM, the first node `_gateway IP_ADDRESS` allowed me to Plonk from the VM to my host computer. However, I have been unable to Plonk the other way. It may be because the connection from within the VM is taken to be wired with a different set of IPs to my local network on the host computer (thoughts?)
6. Testing on an AWS EC2 instance, everything works however because I'm not in the same local network, I cannot Plonk between it and my local machine. The instance only picks up itself as a node.
7. I'll be testing out a Docker image of this shortly and get back to you!

Cheers, Patrick

**Comment by gomesdigital** [comment]
Hey @patrickm663,

Awesome to see you're getting involved!

You're correct about the port mapping on Termux. For that reason, if you're not root, you will only be able to shoot files from your Android elsewhere, not from anywhere to it - would be a great feature though.. :D

Your VM can interact with the service of your host because it is served on port 22, but the other way around will require some extra steps. You will need to setup port forwarding from an unused port on your host to the port where your ssh service is running on your VM.  You can check which port your ssh service is using with: ```cat /etc/ssh/sshd_config | grep Port```, and then forward an unused port on your host to that port through your hypervisor's UI.

Thereafter, you'd still need to modify the script to perform a network scan for the port that you chose to use. In light of this, I've created issue #7 which you might be interested in. Let me know your thoughts on that.

**A notable mention:**
There are other ways to do this if you like, you just won't have the portability of having a script. 

1. In the case of your VM, you can create a shared folder, which both your host and VM can read and write to. 

2. In the case of EC2 (or any other computer), you can use ```scp``` or ```rsync``` to move files around, but you'll have to note the IP of your instance of course.  

But you're absolutely right. It is probably worth including some instructions to setup SSH. It would be even better if we can get that going in the installation scripts though. If you're interested, please submit a pull request ( along with that Dockerfile ) and we can see that be included in 1.0.3!

**Comment by gomesdigital** [comment]
Resolved as of [a5b65cb517cc9af59411962616fc4199e6434466](https://github.com/gomesdigital/AirPlonk/commit/a5b65cb517cc9af59411962616fc4199e6434466).
